name: STAGING

on:
  pull_request:
    branches: ["staging"]
    types: [closed]

jobs:
  test:
    runs-on: [self-hosted,test]
    steps:
      - uses: actions/checkout@v3

      - name: docker build nginx hello world
        run: docker build -t lama202/nginixtest:stagingnew /nodehello

      - name: login to docker
        run: docker login -u lama202 -p dckr_pat_-Dxta0ajdrHOHC_-CDyGyMnVFK0
      - run: docker push lama202/nginixtest:stagingnew
    
  Deploy_staging:
      runs-on: [self-hosted, testrunner]
      needs: test
      steps:
        - name: pull docker images
          run: docker pull lama202/nginixtest:stagingnew

        - name run staging image
        run: docker run -d - 3000:80 lama202/nginixtest:stagingnew
    